AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CalibrateStart<<STAGE>>

Parameters:
  Bucket:
    Type: String
    Default: charge-device-lambda-function-dev
    AllowedValues:
      - charge-device-lambda-function-dev
      - charge-device-lambda-function-tst
      - charge-device-lambda-function-acpt
      - charge-device-lambda-function-prod
  Stage:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Tst
      - Acpt
      - Prod    

Globals:
  Function:
    MemorySize: 512
    Runtime: python3.9
    Timeout: 30
    Environment:
      Variables:
        STAGE: !Sub '${Stage}'
        Bucket: !Sub '${Bucket}'

Mappings: 
  EnvironmentMap: 
    Dev: 
      LogGroupRetentionDays: 1
    Tst: 
      LogGroupRetentionDays: 7
    Acpt: 
      LogGroupRetentionDays: 31
    Prod:
      LogGroupRetentionDays: 365

Resources:
  CalibrateStartFunction<<STAGE>>:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Timeout: 30
      CodeUri: function.zip
      FunctionName: !Sub 'CalibrateStartFunction${Stage}'
      Role: arn:aws:iam::<<ACCOUNT_ID>>:role/<<ACCOUNT_USER>>
      ReservedConcurrentExecutions: 1
      Layers: # An optional list Lambda Layers to use
        - !Ref CalibrateStartLayer<<STAGE>>
  CalibrateStartLogGroup<<STAGE>>:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: 
        Fn::Sub:
          - '/aws/lambda/${name}'
          - name: !Sub 'CalibrateStartFunction${Stage}'
      RetentionInDays: !FindInMap [ 'EnvironmentMap', !Ref 'Stage', 'LogGroupRetentionDays' ]
  CalibrateStartLayer<<STAGE>>:
    Type: 'AWS::Serverless::LayerVersion'
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      CompatibleRuntimes:
        - python3.9
      ContentUri: layer.zip
      Description: requirements-joblib-layer
      LayerName: CalibrateStartLayer<<STAGE>>
  CalibrateStartUrl<<STAGE>>:
    Type: 'AWS::Lambda::Url'
    Properties:
        TargetFunctionArn: !Ref CalibrateStartFunction<<STAGE>>
        AuthType: NONE
  CalibrateStartUrlPermission<<STAGE>>:
    Type: 'AWS::Lambda::Permission'
    Properties:
        FunctionName: !Ref CalibrateStartFunction<<STAGE>>
        Principal: '*'
        Action: lambda:InvokeFunctionUrl
        FunctionUrlAuthType: NONE

Outputs:
  CalibrateStartFunction<<STAGE>>ARN:
    Description: Logical id (ARN) of the lambda
    Value:
      !GetAtt CalibrateStartFunction<<STAGE>>.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CalibrateStartFunction${Stage}ARN'
  CalibrateStartLayer<<STAGE>>ARN:
    Description: Logical id (ARN) of the layer
    Value:
      !Ref CalibrateStartLayer<<STAGE>>
    Export:
      Name: !Sub '${AWS::StackName}-CalibrateStartLayer<<TIMESTAMP>>ARN'