AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: ChargeProgress<<STAGE>>

Parameters:
  Bucket:
    Type: String
    Default: charge-device-lambda-function-dev
    AllowedValues:
      - charge-device-lambda-function-dev
      - charge-device-lambda-function-tst
      - charge-device-lambda-function-acpt
      - charge-device-lambda-function-prod
  BucketData:
    Type: String
    Default: charge-device-lambda-data-dev
    AllowedValues:
      - charge-device-lambda-data-dev
      - charge-device-lambda-data-tst
      - charge-device-lambda-data-acpt
      - charge-device-lambda-data-prod
  Stage:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Tst
      - Acpt
      - Prod

Globals:
  Function:
    MemorySize: 512
    Runtime: python3.9
    Timeout: 30
    Environment:
      Variables:
        STAGE: !Sub '${Stage}'
        Bucket: !Sub '${Bucket}'
        BucketData: !Sub '${BucketData}'

Mappings: 
  EnvironmentMap: 
    Dev: 
      LogGroupRetentionDays: 1
    Tst: 
      LogGroupRetentionDays: 7
    Acpt: 
      LogGroupRetentionDays: 31
    Prod:
      LogGroupRetentionDays: 365

Resources:
  ChargeProgressFunction<<STAGE>>:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: function.zip
      FunctionName: !Sub 'ChargeProgressFunction${Stage}'
      Role: arn:aws:iam::<<ACCOUNT_ID>>:role/<<ACCOUNT_USER>>
      ReservedConcurrentExecutions: 1
      Layers: # An optional list Lambda Layers to use
        - !Ref ChargeProgressLayer<<STAGE>>
  ChargeProgressLogGroup<<STAGE>>:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: 
        Fn::Sub:
          - '/aws/lambda/${name}'
          - name: !Sub 'ChargeProgressFunction${Stage}'
      RetentionInDays: !FindInMap [ 'EnvironmentMap', !Ref 'Stage', 'LogGroupRetentionDays' ]
  ChargeProgressLayer<<STAGE>>:
    Type: 'AWS::Serverless::LayerVersion'
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      CompatibleRuntimes:
        - python3.9
      ContentUri: layer.zip
      Description: requirements-joblib-layer
      LayerName: ChargeProgressLayer<<STAGE>>
  ChargeProgressUrl<<STAGE>>:
    Type: 'AWS::Lambda::Url'
    Properties:
        TargetFunctionArn: !Ref ChargeProgressFunction<<STAGE>>
        AuthType: NONE
  ChargeProgressUrlPermission<<STAGE>>:
    Type: 'AWS::Lambda::Permission'
    Properties:
        FunctionName: !Ref ChargeProgressFunction<<STAGE>>
        Principal: '*'
        Action: lambda:InvokeFunctionUrl
        FunctionUrlAuthType: NONE


Outputs:
  ChargeProgressFunction<<STAGE>>ARN:
    Description: Logical id (ARN) of the lambda
    Value:
      !GetAtt ChargeProgressFunction<<STAGE>>.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ChargeProgressFunction${Stage}ARN'
  ChargeProgressLayer<<STAGE>>ARN:
    Description: Logical id (ARN) of the layer
    Value:
      !Ref ChargeProgressLayer<<STAGE>>
    Export:
      Name: !Sub '${AWS::StackName}-ChargeProgressLayer<<TIMESTAMP>>ARN'