#! /bin/bash

# Fill in the URL of the lambda function the webapp uses. Be sure to leave out the https:// part
# example:
# export CALIBRATE_START_LAMBDA_FUNCTION_URL=g5swxdn56l3v6g3k1g66lj0ahq0jbhhi.lambda-url.eu-north-1.on.aws
export CALIBRATE_START_LAMBDA_FUNCTION_URL=<>
export CHARGE_START_LAMBDA_FUNCTION_URL=<>
export CHARGE_PROGRESS_LAMBDA_FUNCTION_URL=<>
export PERFORM_REGISTRATION_LAMBDA_FUNCTION_URL=<>
export CALCULATE_AVOIDED_EMISSIONS_LAMBDA_FUNCTION_URL=<>

docker build --tag eks-python-web:latest --file Dockerfile . --build-arg CALIBRATE_START_LAMBDA_FUNCTION_URL=$CALIBRATE_START_LAMBDA_FUNCTION_URL --build-arg CHARGE_START_LAMBDA_FUNCTION_URL=$CHARGE_START_LAMBDA_FUNCTION_URL --build-arg CHARGE_PROGRESS_LAMBDA_FUNCTION_URL=$CHARGE_PROGRESS_LAMBDA_FUNCTION_URL --build-arg CALCULATE_AVOIDED_EMISSIONS_LAMBDA_FUNCTION_URL=$CALCULATE_AVOIDED_EMISSIONS_LAMBDA_FUNCTION_URL 

docker run -p 80:80 eks-python-webs